import type { Contact, Group } from "./types"

export function generateSampleData() {
  const sampleGroups: Group[] = [
    { id: 1, name: "가족" },
    { id: 2, name: "그룹1" },
    { id: 3, name: "그룹2" },
    { id: 4, name: "그룹3" },
    { id: 5, name: "그룹4" },
    { id: 6, name: "그룹5" },
    { id: 7, name: "그룹6" },
    { id: 8, name: "그룹7" },
    { id: 9, name: "그룹8" },
    { id: 10, name: "그룹9" },
    { id: 11, name: "그룹10" }

  ]

  const sampleContacts: Contact[] = [
        {
            "ID": "2",
            "Group": "그룹2",
            "Check": true,
            "Conversation": "MuS_0004 쏘지",
            "Name": "쏘지",
            "Phone_Number": "010-9958-7875",
            "Email": "so910506@naver.com",
            "Definition1": "서울 종로구 지봉로17길 36 4층 (창신동)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/ssoji",
            "Start_Or": "",
            "Whether_Or": "3",
            "Checklist": "불일치",
            "Dialogue_Name": "MuS_0004 쏘지",
            "Change_Name": "MuS 0004 쏘지"
        },
        {
            "ID": "3",
            "Group": "그룹3",
            "Check": true,
            "Conversation": "MuS_5_쏜가먼츠",
            "Name": "쏜가먼츠",
            "Phone_Number": "010-9958-7875",
            "Email": "sown666@naver.com",
            "Definition1": "부산광역시 부산진구 만리산로 42 2층",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/sowngarments",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "불일치",
            "Dialogue_Name": "MuS_5_쏜가먼츠",
            "Change_Name": ""
        },
        {
            "ID": "4",
            "Group": "그룹4",
            "Check": true,
            "Conversation": "MuS 9_씨스앤브로",
            "Name": "씨스앤브로",
            "Phone_Number": "010-3227-8450",
            "Email": "family@sisnbro.me",
            "Definition1": "서울 중구 청구로1길 23 114동 1101호",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/sisnbro",
            "Start_Or": "",
            "Whether_Or": "3",
            "Checklist": "",
            "Dialogue_Name": "MuS 9_씨스앤브로",
            "Change_Name": ""
        },
        {
            "ID": "5",
            "Group": "그룹5",
            "Check": true,
            "Conversation": "MuS 0011_씨쏘",
            "Name": "씨쏘",
            "Phone_Number": "010-6396-7020",
            "Email": "see__saw@naver.com",
            "Definition1": "경기도 파주시 미래로310번길 170-2 102동 202호 (동패동, 더테라스)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/seesaw",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "",
            "Dialogue_Name": "MuS 0011_씨쏘",
            "Change_Name": ""
        },
        {
            "ID": "6",
            "Group": "그룹6",
            "Check": true,
            "Conversation": "MuS 0012_씨앤립",
            "Name": "씨앤립",
            "Phone_Number": "010-2088-4400",
            "Email": "seanlip@naver.com",
            "Definition1": "서울시 강서구 강서로 18바길 5, B01호(화곡동, 화종빌라)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/seanlip",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "",
            "Dialogue_Name": "MuS 0012_씨앤립",
            "Change_Name": ""
        },
        {
            "ID": "7",
            "Group": "그룹7",
            "Check": true,
            "Conversation": "MuS_0004_쏘지",
            "Name": "씨유아르보",
            "Phone_Number": "010-9289-9459",
            "Email": "seeuarvo@naver.com",
            "Definition1": "경기 수원시 팔달구 효원로 303 713호(인계동, 삼호파크타워)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/seeuarvo",
            "Start_Or": "",
            "Whether_Or": "3",
            "Checklist": "",
            "Dialogue_Name": "MuS_0004_쏘지",
            "Change_Name": ""
        },
        {
            "ID": "8",
            "Group": "그룹8",
            "Check": true,
            "Conversation": "MuS 0017_에스더블류앤엘 시원리",
            "Name": "에스더블류앤엘 시원리",
            "Phone_Number": "010-5199-7778",
            "Email": "office@ephe-store.com",
            "Definition1": "서울특별시 중구 동호로14길 47 BIFA빌딩 5층 502호(신당동) 에페",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/ephe",
            "Start_Or": "",
            "Whether_Or": "3",
            "Checklist": "일치",
            "Dialogue_Name": "MuS 0017_에스더블류앤엘 시원리",
            "Change_Name": ""
        },
        {
            "ID": "9",
            "Group": "그룹9",
            "Check": true,
            "Conversation": "MuS 0039_에스틸리",
            "Name": "에스틸리",
            "Phone_Number": "010-6848-9865",
            "Email": "still12oclock@gmail.com",
            "Definition1": "경기 남양주시 화도읍 마석중앙로37번길 45 305호(별나라프라자)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/st12",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "일치",
            "Dialogue_Name": "MuS 0039_에스틸리",
            "Change_Name": ""
        },
        {
            "ID": "10",
            "Group": "그룹10",
            "Check": true,
            "Conversation": "MuS 0047_댄앤나우",
            "Name": "댄앤나우",
            "Phone_Number": "010-6869-6698",
            "Email": "then3ow@gmail.com",
            "Definition1": "서울 중랑구 상봉로28길 60 (망우동)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/thenow",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "일치",
            "Dialogue_Name": "MuS 0047_댄앤나우",
            "Change_Name": ""
        },
        {
            "ID": "11",
            "Group": "그룹11",
            "Check": true,
            "Conversation": "MuS 0053_더 슬렌티드",
            "Name": "더 슬렌티드",
            "Phone_Number": "010-3887-3589",
            "Email": "eominic@naver.com",
            "Definition1": "대구 달서구 조암로 89-9 (월성동)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/theslanted",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "일치",
            "Dialogue_Name": "MuS 0053_더 슬렌티드",
            "Change_Name": ""
        },
        {
            "ID": "12",
            "Group": "그룹12",
            "Check": true,
            "Conversation": "MuS 0058_더 퍼펙트 핸드",
            "Name": "더 퍼펙트 핸드",
            "Phone_Number": "010-9138-7882",
            "Email": "petrichor1027@gmail.com",
            "Definition1": "서울특별시 종로구 충신4길 27 (충신동)",
            "Definition2": "",
            "Definition3": "",
            "Memo": "https://www.musinsa.com/brands/theperfecthand",
            "Start_Or": "",
            "Whether_Or": "2",
            "Checklist": "일치",
            "Dialogue_Name": "MuS 0058_더 퍼펙트 핸드",
            "Change_Name": ""
        }
    
]
  return { sampleContacts, sampleGroups }
}

